### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ssoonmi** [jm-riley/cloudsound#5]
### Login/Signup Form
- [x] Looks like the modal cuts off the white background of the login/signup form before the text at the bottom of the form ends
- [x] needs a demo login
- [x] clicking anywhere outside the actual form should close the modal, not just the (x) button

### Logout
- [x] clicking anywhere outside of the logout button menu should close that menu (one way you can accomplish this is using a modal)
- [x] the entire dropdown has a cursor pointer, but only the individual li's should
- [x] the individual li's in the dropdown menu should span the entire ul and should have a padding
- [x] the onClick for logging out should be on the li itself, not on the text

Looks great! keep up the good work!

**Comment by ssoonmi** [comment]
- one more thing! style the demo log in button on the login/signup pages so that it looks like it should be there! Maybe style it to look like the submit button

**Comment by jm-riley** [comment]
think I might decrease the width on the demo and submit buttons
